name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Heroku # naam van mijn environment op GitHub
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.03cf8aa4-bfc6-4f50-b749-befd4d31d2d1}}
          heroku_app_name: share-a-meal-2191148
          heroku_email: jonah.eikenhorst@gmail.com